version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "auth0-practice"
s3_bucket = ""
s3_prefix = ""
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
